### ISSUE TITLE
Zusammenführung Implementierungen Vorverarbeitung

### ISSUE THREAD

**Issue by sonrisa0** [netGed/WebScience24#4]

**Comment by Imran1221** [comment]
falls wir @netGed aka Chris sein Notebook als finalen Notebook (mit eventuellen Ergänzungen) nehmen, wäre es nice unter jedem Schritt eine kurze Beschreibung hinzufügen, um zu verstehen was genau gemacht wird...
+ korrigieren der namenskonvetionen, bsp. wird  `df[tweet_cleaned_step3]` geschrieben, obwohl es laut Überschrift der vierte schritt ist...

**Comment by nasibatuychieva** [comment]
Ich würde das an unserem Termin zusammen absprechen, diskutieren und dann entscheiden.
